// Indian states and major cities in alphabetical order
export const INDIA_LOCATIONS = [
  'Agra, Uttar Pradesh',
  'Ahmedabad, Gujarat',
  'Ajmer, Rajasthan',
  'Aligarh, Uttar Pradesh',
  'Allahabad, Uttar Pradesh',
  'Amravati, Maharashtra',
  'Amritsar, Punjab',
  'Aurangabad, Maharashtra',
  'Bangalore, Karnataka',
  'Bareilly, Uttar Pradesh',
  'Belgaum, Karnataka',
  'Bellary, Karnataka',
  'Bhavnagar, Gujarat',
  'Bhilai, Chhattisgarh',
  'Bhopal, Madhya Pradesh',
  'Bhubaneswar, Odisha',
  'Bikaner, Rajasthan',
  'Chandigarh, Punjab',
  'Chennai, Tamil Nadu',
  'Coimbatore, Tamil Nadu',
  'Cuttack, Odisha',
  'Dehradun, Uttarakhand',
  'Delhi, NCR',
  'Dhanbad, Jharkhand',
  'Durg, Chhattisgarh',
  'Durgapur, West Bengal',
  'Erode, Tamil Nadu',
  'Faridabad, Haryana',
  'Firozabad, Uttar Pradesh',
  'Ghaziabad, Uttar Pradesh',
  'Goa, Goa',
  'Gorakhpur, Uttar Pradesh',
  'Gulbarga, Karnataka',
  'Guntur, Andhra Pradesh',
  'Gurgaon, Haryana',
  'Guwahati, Assam',
  'Gwalior, Madhya Pradesh',
  'Hubli, Karnataka',
  'Hyderabad, Telangana',
  'Indore, Madhya Pradesh',
  'Jabalpur, Madhya Pradesh',
  'Jaipur, Rajasthan',
  'Jalandhar, Punjab',
  'Jalgaon, Maharashtra',
  'Jammu, Jammu and Kashmir',
  'Jamnagar, Gujarat',
  'Jamshedpur, Jharkhand',
  'Jhansi, Uttar Pradesh',
  'Jodhpur, Rajasthan',
  'Kakinada, Andhra Pradesh',
  'Kannur, Kerala',
  'Kanpur, Uttar Pradesh',
  'Kochi, Kerala',
  'Kolhapur, Maharashtra',
  'Kolkata, West Bengal',
  'Kollam, Kerala',
  'Kota, Rajasthan',
  'Kottayam, Kerala',
  'Kozhikode, Kerala',
  'Kurnool, Andhra Pradesh',
  'Lucknow, Uttar Pradesh',
  'Ludhiana, Punjab',
  'Madurai, Tamil Nadu',
  'Malappuram, Kerala',
  'Mangalore, Karnataka',
  'Mathura, Uttar Pradesh',
  'Meerut, Uttar Pradesh',
  'Moradabad, Uttar Pradesh',
  'Mumbai, Maharashtra',
  'Muzaffarnagar, Uttar Pradesh',
  'Mysore, Karnataka',
  'Nagpur, Maharashtra',
  'Nanded, Maharashtra',
  'Nashik, Maharashtra',
  'Nellore, Andhra Pradesh',
  'Noida, Uttar Pradesh',
  'Palakkad, Kerala',
  'Patna, Bihar',
  'Pune, Maharashtra',
  'Raipur, Chhattisgarh',
  'Rajahmundry, Andhra Pradesh',
  'Rajkot, Gujarat',
  'Ranchi, Jharkhand',
  'Rourkela, Odisha',
  'Saharanpur, Uttar Pradesh',
  'Salem, Tamil Nadu',
  'Sangli, Maharashtra',
  'Shimla, Himachal Pradesh',
  'Siliguri, West Bengal',
  'Solapur, Maharashtra',
  'Srinagar, Jammu and Kashmir',
  'Surat, Gujarat',
  'Thiruvananthapuram, Kerala',
  'Thrissur, Kerala',
  'Tiruchirappalli, Tamil Nadu',
  'Tirunelveli, Tamil Nadu',
  'Tiruppur, Tamil Nadu',
  'Udaipur, Rajasthan',
  'Ujjain, Madhya Pradesh',
  'Vadodara, Gujarat',
  'Varanasi, Uttar Pradesh',
  'Vasai-Virar, Maharashtra',
  'Vijayawada, Andhra Pradesh',
  'Visakhapatnam, Andhra Pradesh',
  'Warangal, Telangana',
  'Other',
];

export const CROP_TYPES = [
  'Rice',
  'Wheat',
  'Maize',
  'Pulses',
  'Sugarcane',
  'Cotton',
  'Jute',
  'Tea',
  'Coffee',
  'Rubber',
  'Tomatoes',
  'Potatoes',
  'Onions',
  'Cauliflower',
  'Cabbage',
  'Brinjal',
  'Okra',
  'Peas',
  'Beans',
  'Carrots',
  'Radish',
  'Cucumbers',
  'Pumpkin',
  'Bottle Gourd',
  'Bitter Gourd',
  'Ridge Gourd',
  'Chillies',
  'Capsicum',
  'Spinach',
  'Coriander',
  'Mint',
  'Fenugreek',
  'Mangoes',
  'Bananas',
  'Grapes',
  'Oranges',
  'Apples',
  'Guava',
  'Papaya',
  'Pomegranate',
  'Watermelon',
  'Muskmelon',
  'Other',
];
